# Generated by Django 3.2.14 on 2022-07-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='heading',
            new_name='task_name',
        ),
    ]
