# Generated by Django 3.2.14 on 2022-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_heading_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
