# Generated by Django 3.2.14 on 2022-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='modified_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='ID',
            field=models.AutoField(default=23, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
