# Generated by Django 3.2.14 on 2022-07-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20220720_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ID',
            new_name='id',
        ),
    ]
